[font]
size = 16
offset.y = 3
glyph_offset.y = 2

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.normal]
# family = "JetBrains Mono"
# style = "Regular"
family = "SFMono Nerd Font"

[general]
import = [
    "gnome_terminal"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
padding.x = 5
padding.y = 5

[colors.primary]
background = '#1c1c1f'
foreground = '#ffffff'

[colors.normal]
black   = '#171717'
red     = '#c01c28'
green   = '#2ec27e'
yellow  = '#f5c211'
blue    = '#1e78e4'
magenta = '#a347ba'
cyan    = '#2aa1b3'
white   = '#d0cfcc'

[colors.bright]
black   = '#5e5c64'
red     = '#f66151'
green   = '#33da7a'
yellow  = '#e9ad0c'
blue    = '#2a7bde'
magenta = '#c061cb'
cyan    = '#33c7de'
white   = '#ffffff'

