#!/usr/bin/env bash

selected=$(find /mnt/d/dev -mindepth 1 -maxdepth 3 -type d | fzf)
if [[ -z $selected ]]; then exit 0; fi
name=$(basename "$selected" | tr . _)
if ! tmux has-session -t=$name 2> /dev/null; then
    tmux new-session -ds $name -c $selected
fi
tmux switch-client -t $name
