#!/usr/bin/env bash

selected=$(find /mnt/d/dev ~/dotfiles -mindepth 0 -maxdepth 3 -type d | fzf)
if [[ -z $selected ]]; then exit 0; fi
name=$(basename "$selected" | tr . _)
if ! tmux has-session -t=$name 2> /dev/null; then
    tmux new-session -ds $name -c $selected
fi

if [[ -z $TMUX ]] then
    tmux attach-session -t $name
else 
    tmux switch-client -t $name
fi
